# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/legislationForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormLegislation(object):
    def setupUi(self, FormLegislation):
        FormLegislation.setObjectName("FormLegislation")
        FormLegislation.resize(1268, 770)
        self.btnExit = QtWidgets.QPushButton(FormLegislation)
        self.btnExit.setGeometry(QtCore.QRect(1020, 680, 93, 28))
        self.btnExit.setObjectName("btnExit")

        self.retranslateUi(FormLegislation)
        QtCore.QMetaObject.connectSlotsByName(FormLegislation)

    def retranslateUi(self, FormLegislation):
        _translate = QtCore.QCoreApplication.translate
        FormLegislation.setWindowTitle(_translate("FormLegislation", "Form"))
        self.btnExit.setText(_translate("FormLegislation", "Exit"))
