# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/uyapForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormUYAP(object):
    def setupUi(self, FormUYAP):
        FormUYAP.setObjectName("FormUYAP")
        FormUYAP.resize(1139, 769)

        self.retranslateUi(FormUYAP)
        QtCore.QMetaObject.connectSlotsByName(FormUYAP)

    def retranslateUi(self, FormUYAP):
        _translate = QtCore.QCoreApplication.translate
        FormUYAP.setWindowTitle(_translate("FormUYAP", "Form"))
